version: 2.1

orbs:
  percy: percy/agent@0.1.2

jobs:
  test_1:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Percy test 1
          command: npx percy exec -- npm run test-1

  test_2:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Percy test 2
          command: npx percy exec -- npm run test-2

  test_3:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Percy test 3
          command: npx percy exec -- npm run test-3

workflows:
  version: 2
  test_and_finalize:
    jobs:
      - test_1
      - test_2
      - test_3
      - percy/finalize_all:
          requires:
            - test_1
            - test_2
            - test_3
